### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by Rockiii87** [ghmartin77/SmartLEDLamp#1]
Hi, i just didnt found out how to compile the sketch.
Do i have to use arduino or atom?
Or maybe even esplorer?

Please let me know how to use this script....

Thanks in advance!

**Comment by ghmartin77** [comment]
Hi Rockiii87,

You can either compile using the toolchain that comes with ArduinoSDK for ESP8266 or -probably easiest way- ArduinoIDE (with ESP8266 Boardmanager extension). In the latter case rename LEDLamp.cpp to <folder_containing_file>.ino (probably SmartLEDLamp.ino. Open this file with ArduinoIDE, select the right target board and compile.
Please also note the hints on the Github repository entry page under section "How to Build", especially what additional libraries you will need to include.

Best regards,
ghmartin77

**Comment by ghmartin77** [comment]
With per1234's pull request "compilability" with Arduino IDE is now built-in.
