### ISSUE TITLE
Compiling runs into errors.

### ISSUE THREAD

**Issue by Rockiii87** [ghmartin77/SmartLEDLamp#3]
Hey Guys,

Arduino is supported now, thanks for this.

But i cant find a way out of these errors until now.

```
LEDLamp.cpp:44: error: 'IRrecv' does not name a type

 IRrecv irrecv(PIN_RECV_IR);

 ^

sketch\LEDLamp.cpp: In function 'void setup()':

LEDLamp.cpp:378: error: 'irrecv' was not declared in this scope

  irrecv.enableIRIn(); // Start the receiver

  ^

sketch\LEDLamp.cpp: In function 'void loop()':

LEDLamp.cpp:688: error: 'decode_results' was not declared in this scope

  decode_results results;

  ^

LEDLamp.cpp:688: error: expected ';' before 'results'

  decode_results results;

                 ^

LEDLamp.cpp:694: error: 'irrecv' was not declared in this scope

  if (irrecv.decode(&results)) {

      ^

LEDLamp.cpp:694: error: 'results' was not declared in this scope

  if (irrecv.decode(&results)) {

                     ^


exit status 1
'IRrecv' does not name a type
```

As i dont want to use IR, i think i can throw out the IRRemote lib?

**Comment by ghmartin77** [comment]
Probably you don't have installed the IRRemote library mentioned in the build descriptions:
IRemoteESP8266 - https://github.com/sebastienwarin/IRremoteESP8266

Nevertheless, if you don't want to use IR, just remove anything related to it from the sources. I'll introduce a #define to make it easier when I've got time to do so.

**Comment by ghmartin77** [comment]
Enhanced with commit last commit.
Check out "#define IR_ENABLE" in defines.h.
